server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://slc11fsp.us.oracle.com:3306/test?useUnicode=true&characterEncoding=utf8mb4
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名转换
